### ISSUE TITLE
RestartReferent

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/iso-19148#1]
SIS008 makes the following request: 

> The class RestartReferent, as defined in OGC InfraGML 1.0: Part 0 – LandInfra Core - Encoding Standard, should be added to the standard to allow for “broken chainage” which is common in many infrastructure applications, especially applications involving railway networks

This topic – sometimes also referred to as “Station equations” - has been a known issue in 19148. InfraGML addresses it as follows:

> The agreed upon solution is to propose an additional Referent attribute called restartValue which behaves similar to the LinearElement.startValue and addresses the more general problem of restarting the measure value at the Referent location. This is achieved herein with the addition of a RestartReferent subtype of the original 19148 Referent, though an eventual change to 19148 itself (adding this optional attribute to Referent) may obviate the need for this extension

Thus, this proposed change would translate to the following addition to the LR_Referent class:
![diego](https://user-images.githubusercontent.com/7501876/51532537-ad8dc380-1e40-11e9-84f8-5a4501afa342.png)

Described as:
 
**Operation: restartValue**
The optional operation “restartValue” returns a known measure value at the location of the LR_Referent along the LR_LinearElement for the specified Linear Referencing Method. This measure value represents a new start to be used for measurements made after such location along the LR_LinearElement.
 
Any objections to this proposed solution?
 
Best regards,
Diego

**Comment by diegoalexdiaz** [comment]
Thanks for your proposal Knut. I am ok with restartValue being added as an attribute thanks to your LR_ValueExpression proposal (which includes the required LRM context). I also agree with you that LR_ValueExpression is a better name than StartValue for this type.

_Re: I would prefer to have the operations on LR_ILinearElement as attributes as well_

It seems to me that it would only be possible for the startValue operation. The other operations in LR_ILinearElement can't be turned into attributes as they require additional arguments:

- measure (measureAttribute: CharacterString = defaultLength): Measure
- translateToInstance (sourceLocation: LR_PositionExpression, targetInstance: LR_LinearElement, targetLRM): LR_DistanceExpression
- translateToType (sourceLocation: LR_PositionExpression, targetType: CharacterString, targetLRM): LR_PositionExpression[ ]

**Comment by jetgeo** [comment]
One issue that we need to be aware of with my proposed solution is the backwards compatibility. GML 3.3 has been implemented in, e.g. InfraGML, with the startValue datatype. A new version of GML will be needed based on the revision anyhow, but we don't change things only to change them. In my opinion, the proposed solution is an improvement that can be ranked above backward compatibility. 

On LR_ILinearelement: I suppose the solution is to keep the interface as it is, but to implement the operations measure and startValue in a LinearElement class, as has been done in GML 3.3. 
Ref also https://github.com/ISO-TC211/iso-19148/issues/3#issuecomment-457217229.

**Comment by dloukes** [comment]
agree with the need to address this functionality and with the approach proposed
