### ISSUE TITLE
Type and Interface

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/iso-19148#2]
All “Type” classes in the model must be changed to “Interface”, according to ISO 19103:2015 Annex B. That can be done automatically in the model, but will probably require some manual work in the document.

**Comment by diegoalexdiaz** [comment]
Thanks Knut for raising this detail. I like it and don't mind updating the document.

**Comment by jetgeo** [comment]
There are no special rules for the names of interfaces. 
But we need to consider the level of abstraction for the model. I believe this model shall be at the "Conceptual Schema - Abstract Schemas" level according to ISO 19103. Right now, we have a mix of featuretypes (application schema level) and types/interfaces (abstract schema level). I believe most of the classes shall be interfaces, but some may also be datatypes, or have no stereotype at all. 
Alternatively, we may use the existing application schema package for some feature types.
