### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/iso-19148#3]
We are trying to get rid of them in ISO/TC 211, they are not needed as long as a element name is unique within a package. GML 3.3 does not have prefixes. I suggest we remove them in the revision. E.g. LR_Referent --> Referent.

**Comment by diegoalexdiaz** [comment]
In general, I don't mind including the dropping of these prefixes. There are a couple of questions though:

- ISO 19148 defines two types with the same name but different prefix: LR_Feature and LE_Feature. Dropping prefixes would force us to rename one of them (probably LE_Feature). May not be easy to come up with a good name that everyone likes for it though.

- What are the other standards doing in their documents' content to differentiate between references to an interface vs. references to the underlying concept? Do they use italics or quotes for interface names?

e.g. It is not necessary that the _Feature_ instance that owns a _Referent_ instance be the same _Feature_ instance that is the linear element for the _PositionExpression_ containing that _Referent_ instance.

**Comment by jetgeo** [comment]
Good observations, Diego. 

- As I understand it, LR_Feature is the class that implements the interface LR_ILinearElement (ISO 19148, section 6.2.5). In GML 3.3 this is replaced by the class LinearElement (GML 3.3, section 9.3.5).
My suggestion is to rename the class LR_Feature to LinearElement.
- LE_Feature class is a subtype of LR_Feature, with optional attribute "event" (ISO 19148, section 6.6.3). I have never really understood the use of that class, and the standard kind of says that is is unneccessary as well: 
> "An application schema is not required to have an explicit LE_Feature subtype. 
Instead, it can create LE_Feature instances by adding the LR_ILinearElement interface and event attribute(s)  to existing application-specific feature classes, such as Road"

My suggestion is to remove LE_Feature. It is not implemented in GML 3.3.

On your second bullet point: I am afraid I don't understand the question. Could you draw a figure to explain it?

**Comment by diegoalexdiaz** [comment]
_Re: LE_Feature_

I agree this class may eventually go away as part of the proposed simplification effort. That tells me we rather pospone and revisit the dropping of prefixes after we've done with such simplification so we can have a better picture of how it will affect the entire 19148 model.

_Re: second bullet_

Sorry I wasn't clear. I was only referring to how paragraphs in documents read with and without prefixes. With prefixes, it is very clear when a paragraph is referring to a type vs. when it is referring to a concept. My question was about understanding whether other ISO documents that already dropped prefixes were doing something special to convey it is referring to a type or a concept (e.g. types in italics).

e.g. A random paragraph with prefixes:

> It is not necessary that the LR_Feature instance that owns a LR_Referent instance be the same LR_Feature instance that is the linear element for the LR_PositionExpression containing that LR_Referent instance.

The same random paragraph without prefixes (types in italics):

> It is not necessary that the _Feature_ instance that owns a _Referent_ instance be the same _Feature_ instance that is the linear element for the _PositionExpression_ containing that _Referent_ instance.

**Comment by jetgeo** [comment]
Yes, I agree that we can postpone the removal of prefixes. It is mainly a editorial change. 
For the second bullet point, I suppose we can look at the new ISO 19107. The old ISO 19107 had prefixes, while the new version does not, and uses interfaces and datatypes in a structured manner.

**Comment by dloukes** [comment]
Before you drop prefixes, you should consider whether this may cause unnecessary confusion for readers who are familiar with previous versions of the standard - and in particular, software developers.

**Comment by jetgeo** [comment]
Agree, we have to think about backwards compatibility and how much work it will be for implementers to upgrade to a new version.
