### ISSUE TITLE
positiveDistanceAlongDirection

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/iso-19148#4]
SIS010 proposes the following change: 

Clause 06.01.1.4.3 and 6.4.1-6.4.3: Propose that we extend with Direction (in relation to the direction of the Linear Element) with the possible values: Same, Opposite

This proposed change would lead the addition of an attribute to the LR_LinearReferencingMethod class as follows:
![diego](https://user-images.githubusercontent.com/7501876/51532990-ea0def00-1e41-11e9-96ae-db7ca6ea29db.png)

Described as:

**Attribute: positiveDistanceAlongDirection : LRO_DistanceAlongDirection = “same”**
The attribute “positiveDistanceAlongDirection” gives the direction used as positive for this Linear Reference Method for measurements along the base element. The default value is same with respect to the direction of the base element for positive, opposite for negative. If “from” and “towards referents” have been specified, then the value of same for positive corresponds to the direction of the “towards referent”.

Any objections to this proposed solution?

Best regards,
Diego

**Comment by diegoalexdiaz** [comment]
This is about the direction of the LRM (full text below).

Their full proposed change also included two more requests that I analyzed last year and concluded they were not appropriate.

_a: Lateral offset
Propose that we extend the possible values 
• from: Left, Right 
• to: Left, Right, Middle, Crossing

b: Vertical offset 
Propose that we extend the possible values 
• from: Above, Below
• to: Above, Below, On_

_**Propose that we extend with Direction (in relation to the direction of the Linear Element) with the 
possible values:
• Same, Opposite**_

**Comment by jetgeo** [comment]
One minor detail: Should the attribute be mandatory or not? Perhaps mandatory with default value "same", as in the figure from @diegoalexdiaz?

**Comment by diegoalexdiaz** [comment]
Thanks for catching this detail Knut. I thought I was being consistent with the existing "positiveLateral/VerticalOffsetDirection" attributes but I wasn't. Thus, I agree it should be mandatory with default value "same".

If we later decide to "simplify" 19148 by turning these into optional attributes with "assumed" positive directions, we should do it for all of them for consistency as well.

**Comment by jetgeo** [comment]
Thanks Diego,
You was consistent with the existing classes, I was not. The figure should then be like this: 

![image](https://user-images.githubusercontent.com/7501876/51686272-62b2ae00-1ff0-11e9-9e6c-c6e4564163d6.png)

**Comment by dloukes** [comment]
agree with the proposed change
