### ISSUE TITLE
Measures with uneven distribution

### ISSUE THREAD

**Issue by diegoalexdiaz** [ISO-TC211/iso-19148#5]
Proposed change SIS011 asks for an example of how 19148 covers Measures with uneven distribution:

> Percentage and normalized are examples interpolative linear referencing methods in Annex C4. Measures with un uneven distribution is however not included which is common when using,among others, ESRI-based solutions.

The best description I've been able to find about how Measures with uneven distribution are addressed by ESRI-solutions can be found [here](https://desktop.arcgis.com/en/arcmap/10.3/guide-books/linear-referencing/about-calibrating-route-measures-using-points.htm).

In summary, it comes down to "calibration ratios" that are computed in between known measure locations. Those ratios are then used to adjust measures. Please an image explaining how to calculate those ratios from that ESRI link below:

![esri 02](https://user-images.githubusercontent.com/46930149/51711520-5895ad00-1ffa-11e9-8279-da6f04674d20.png)

I do not believe the 19148 model covers Measures with uneven distribution, thus, a change to it would be required.

The best solution I've thought of so far involves adding a new optional "calibrationMultiplier" attribute to LR_LinearReferencingMethod as follows:

![sis011](https://user-images.githubusercontent.com/46930149/51711571-72cf8b00-1ffa-11e9-911f-79bae3816c12.png)

Described as:

> **Attribute: calibrationMultiplier : Number = 1**
> The optional attribute "calibrationMultiplier" provides a multiplier measures based on a LR_LinearReferencingMethod should be adjusted by. Implementations of translate operations (e.g. LR_ILinearElement.translateToInstance/translateToType) must take this attribute into account when specified.
> 

With that attribute in place, the example described in that ESRI link would look like:

![esri 01a](https://user-images.githubusercontent.com/46930149/51711642-98f52b00-1ffa-11e9-9464-b07a34c86025.png)

Using this example, any LR_PositionExpression or LE_AtLocation/LE_FromToLocation between the first question mark (start of the linear element) and the known measure of 15 would use an LR_Referent with a restartValue = 1.88 (via LR_DistanceExpression) and an LRM instance with a calibrationRatio of 1/1.431 (computed in ESRI’s example above). In the case of LE_AtLocation/LE_FromToLocation, such LRM instance is referenced by using their overrideAt/From/ToLRM attributes). The calculation of the initial restartValue as well as the calibrationRatios applicable to each range are expected to be done ahead of time (like ESRI’s apps do it).

Note that this solution is not only based on the proposed calibrationMultiplier attribute, but also on the RestartReferent "restartValue" attribute discussed on a parallel thread.

Does this solution make sense? Has GML 3.3 addressed Measures with uneven distribution in a different way?

**Comment by jetgeo** [comment]
It is complicated, but after going through it in detail I believe this makes sense. I cannot find anything about this in GML 3.3, so we have no bindings there.

The figure and example beneath show a speed limit feature located in the network using LE_FromToLocation. Is this in line with your proposal, @diegoalexdiaz ?

![unevendistribution](https://user-images.githubusercontent.com/7501876/51747026-7d485e00-20a8-11e9-87ab-fdcec8530bb0.png)

```
SpeedLimit#8
	speedLimitValue=80
	uom="km/h"
	location (LE_FromToLocation)
		locatingFeature=LinearElement#1
		fromPosition
			distanceAlong=7.0
			referent=Referent#1
			overridingLRM
				...
				...
				calibrationRatio=1/1.431
		toPosition
			distanceAlong=28.0
			referent=Referent#3
			overridingLRM
				...
				...
				calibrationRatio=1/0.775
```

One detail: Should the attribute name be calibrationRatio or calibrationMultiplier?

**Comment by diegoalexdiaz** [comment]
Thanks a lot for reviewing this proposal so quickly, Knut. I agree it is a complicated one and one that I feel may not be "fully matured" yet.

_Re: The figure and example beneath... Is this in line with your proposal_

Great figure and example Knut! Thanks for putting it together. Yes, it is in-line with my proposal. Those "calibrationRatio" attributes advertise that associated measure values (e.g. distanceAlong in your example - 7.0 and 28.0) are the result of adjusting actual distances by a certain factor.

Moreover, illustrating the need to advertise this ratio by using your example, let's say I've got another linear element#2 and one needs to translate an LR_PositionExpression from linear element#1 to it. That would be done by the translateInstance operation on linear element#1:

linearElement#1.translateToInstance( positionExpression, linearElement#2 )

positionExpression's LRM would have calibrationRatio assigned.

The implementation of that operation for linearElement#1 needs to "un-adjust" the measure value in positionExpression by using that calibrationRatio so then it can translate it in terms of the LRM in linearElement#2 (which may or may not have that calibrationRatio attribute).

_Re: Should the attribute name be calibrationRatio or calibrationMultiplier?_

I'm not fully in love with any of them, so I'm hoping others propose a better name. "calibration" sounds discipline-specific. "Ratio" suggests we should explain "a Ratio between what?". "multiplier" might be more generic but it feels like it needs a bit more description in its name.

Maybe something like "measureAdjustmentMultiplier" or "measureAdjustingFactor" ?
