### ISSUE TITLE
"Simplified profile" case study: TN-ITS standard

### ISSUE THREAD

**Issue by diegoalexdiaz** [ISO-TC211/iso-19148#8]
I studied the linear referencing model used by the TN-ITS standard towards identifying opportunities for a simplified profile of ISO 19148. TN-ITS was one of the standards shared by Knut and Jonathan to inspire simplifications. This is the summary of my findings:

1. The TN-ITS model, with one exception, conforms with the “Linearly Located Event” package (which includes conformance with the base “Linear Referencing System” package as well) from 19148.
2. With one exception, the classes and properties that TN-ITS doesn’t implement from those two packages are defined as  “optional” by 19148. Thus, they should not be considered as simplifications.
3. TN-ITS does not change the number of levels involved to get to a linearly referenced location with respect to 19148. The number of levels involved is the same for both.

The exception mentioned in 1) and 2) above has to do with TN-ITS not marking its LinearElement class (NetworkElement) with the core/most fundamental interface in 19148 to identify LinearElements: LR_ILinearElement. This interface in 19148 defines a uniform way to distinguish any object suitable for linear measurements along itself, as well as the fundamental operations needed on it. Thus, it makes sense for it not to be optional.

If TN-ITS’ NetworkElement class implemented 19148’s LR_ILinearElement interface, it would entirely pass the conformance tests for the “Linearly Located Event” package (which includes the base “Linear Referencing System” package). **If that was the case, we could state TN-ITS would be a valid implementation of two of the packages in the 19148 model rather than a simplified version of it.**

Please find below further details supporting these conclusions:

**19148: Linear Referencing System package:**

- TN-ITS directly adopts all classes shown in green below from 19148.
- TN-ITS defines NetworkElement as a “substitute” for LR_LinearElement/LR_Feature (in yellow). That is valid under 19148 as it defines LR_Feature to be optional: An App schema can just implement the LR_ILinearElement interface instead (paragraph 6.2.5.1). However, NetworkElement does not implement LR_ILinearElement (in red), which is the most fundamental interface to identify objects that can act as Linear Elements for Linear Referencing purposes.
- Optional classes in 19148 apparently not needed by TN-ITS in blue.

![tn-its-1](https://user-images.githubusercontent.com/46930149/52435990-264b7b80-2ae1-11e9-8c92-523bbca0f5cf.png)

**19148: Linearly Located Event package:**

The diagram below shows the mapping between TN-ITS classes (orange labels) and 19148’s classes. Optional properties and classes in 19148 are shown in blue.

- The following TN-ITS classes conform to 19148: RoadFeature, LocationReference, LinkReference, SimplePointReference, SimpleLinearReference

- TN-ITS incorrectly claims SimplePointReference and SimpleLinearReference are substitutes for LE_AtLocation and LE_FromToLocation. They correctly implement those two 19148 classes since their “overridingXXXLRM” properties are optional.

- ISO 19148 makes the LE_Feature optional too. An App schema can just implement LR_ILinearElement instead (paragraph 6.6.3.1).

- However, NetworkElement does not implement LR_ILinearElement (in red), which is the most fundamental interface to identify objects that can act as Linear Elements for Linear Referencing purposes.

![tn-its-2](https://user-images.githubusercontent.com/46930149/52436123-6f9bcb00-2ae1-11e9-83a0-fdc8fbbdd058.png)

**Levels required to get to a LR_DistanceExpression:**

![tn-its-3](https://user-images.githubusercontent.com/46930149/52436195-a4a81d80-2ae1-11e9-9710-335e787dcc89.png)

**Comment by jetgeo** [comment]
I agree with most of your conclusions here as well. Some comments:

- The reason TN-ITS does not implement _LR_ILinearElement_ is that the linear element is outside of the specification. TN-ITS itself has no linear elements, it's only refering to an external network. In most cases in Europe it will be a _Link_ or _LinkSequence_ from INSPIRE Road Transport Networks. However, I think it would be good to implement _LR_ILinearElement_ in _NetworkElement_ in TN-ITS, to set requirements for the external network. And actually, I believe it is more correct to describe that _NetworkElement_ **implements** **LR_ILinearElement** than to describe it as a **substitute** for _LR_LinearElement_. 
- TN-ITS does not directly adopt _LR_PositionExpression_. Instead, it has the class _NetworkReference_ with an optional attribute for LRM (_overridingLRM_). LRM is mandatory for _PositionExpression_. The implementation in TN-ITS is more like _LE_Event_ with _LE_EventLocation_. 
- One important modification in TN-ITS is the use of a _defaultLRM_ on the class _RoadFeatureDataset_. This reduces the number of times the LRM has to be given to be known for each _LinearLocation_. But information on a dataset level might be outside of the scope of 19148?
- I do not agree on your observation that TN-ITS falsely claims that SimplePointReference and SimpleLinearReference are substitues for LE_AtLocation and LE_FromLocation. They are substitutes. But it might be better to say that they implement/realize the types from 19148. 

- Finally - could an improved description of the TN-ITS linear location model be an informative annex to ISO 19148, presented as a conformant profile?

**Comment by diegoalexdiaz** [comment]
I greatly appreciate your observations, Knut.

_Re: TN-ITS does not directly adopt LR_PositionExpression._

Thanks for pointing it out, and further explanation. I totally missed it. My bad.

_Re: NetworkElement implements LR_ILinearElement... not a substitute for LR_LinearElement._

Thanks for clarifying. On a related note, that helps me verbalize my issue with LR_LinearElement. That class plays the role of an "**accessor** to the LinearElement implementation", rather than representing the "LinearElement" itself. That's why I raised the possibility of making it optional as a simplification.

_Re: information on a dataset level might be outside of the scope of 19148?_

RoadFeatureDataset is certainly the perfect place for a "defaultLRM" in TN-ITS, but I agree that's a decision at the implementation level that 19148 should not get into.

_Re: They are substitutes. But it might be better to say that they implement/realize the types from 19148._

I'm confused about the correct usage of "substitutes" vs. "implements". In my head, if a class "implements" a concept, it is not substituting it, but, as you say, realizing it in a given context. That's my understanding of what SimplePointReference/SimpleLinearReference do in TN-ITS. Your example of NetworkElement implementing LR_ILinearElement also applies here.

On the other hand, if a class "substitutes" a concept, it is not realizing it, but rather, replacing it with another concept. Maybe the difference is in the semantics of those classes in TN-ITS. Nevertheless, I trust you're judgement here since you're a lot more familiar with TN-ITS than me.

_Re: could an improved description of the TN-ITS linear location model be an informative annex to ISO 19148, presented as a conformant profile?_

If time allows, that sounds like a good idea to me. BTW, we're aiming for a mid-Summer timeframe for the WD, towards having the CD in October.

**Comment by jetgeo** [comment]
Regarding the conformance: 6.6.1 says 

> "An application claiming conformance to this Linearly Located Event package shall support all of the LE classes shown in Figure 44 and all of the LR classes shown in Figure 14 for the Linear Referencing System package on which this package is dependent." TN-ITS does not support all classes from Figure 44. Should the requirement be more specific? The Instant classes are not needed unless time is a factor. An LR_Feature is also described elsewhere to be optional. 

A bit of a hurry here now, but here's a suggested improved version of the relation between TN-ITS and 19148 version 1:

![image](https://user-images.githubusercontent.com/7501876/52865131-25979280-313c-11e9-9e05-555fe373b3e2.png)

**Comment by diegoalexdiaz** [comment]
Thanks for the update. It looks much better than the one you sent me last year.

_Re: Should the requirement be more specific?_

I totally agree. That statement is misleading since, as you describe, there are a number of classes that are described as optional.
