### ISSUE TITLE
"Simplified profile" case study: DATEX II Location Referencing standard

### ISSUE THREAD

**Issue by diegoalexdiaz** [ISO-TC211/iso-19148#9]
I studied the linear referencing model used by the DATEX-II standard towards identifying opportunities for a simplified profile of ISO 19148. DATEX-II was one of the standards shared by Jonathan to inspire simplifications. This is the summary of my findings:

The DATEX-II standard does introduce several simplifications with respect to 19148 (detailed list below). Some of those simplifications would be limiting with respect to 19148’s flexibility while others are based on assumptions that 19148 prefers to be specific about. Nevertheless, I do think there are a few simplifications to 19148 inspired by DATEX II that we should discuss since they would make 19148 more friendly to work with:

1. Optionally allow direct relationships from LR_DistanceExpression to LR_Referent (ala DATEX II). i.e. Not requiring the intermediate LR_AlongReferent or LR_DualAlongReferent classes.
2. Turn positive direction LRM attributes into optional. Assume positive directions for lateral/vertical/along measures if not specified (e.g. right/up/same).
3. Following the philosophy of 1), optionally allow direct relationships from LR_PositionExpression to an LR_ILinearElement implementation. i.e. Not requiring the intermediate LR_LinearElement Union.

Any comments, opinions and reactions about these proposed simplifications to 19148 will be greatly appreciated.

**DATEX II Location Referencing – Detailed Analysis**

DATEX II seems to aim to implement 3 packages from 19148: Linear Referencing System, Linear Referencing Towards Referent and Linearly Located Event.

![datexii](https://user-images.githubusercontent.com/46930149/52640442-79884a00-2ea4-11e9-8cff-61410f44f548.png)

**Comment by diegoalexdiaz** [comment]
I personally like simplification 1).
I'm not a big fan of simplification 2) seems to go against 19148's philosophy of being explicit about positive directions in LRM.
I generally like simplification 3), but turning a class named "LR_LinearElement" into optional in a Linear Referencing model seems odd.

**Comment by jetgeo** [comment]
I agree with your analysis and your conclusions.
I don't like the DATEX II approach with one "DistanceExpression" class for each LRM type (absolute, interpolative). ISO 19148 with one generic class and the position value as Measure and LRM specified for the linear element or for each location is more elegant.
